In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
a = np.array([1,2,3,4,5])

In [6]:
a[0]

np.int64(1)

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [10]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
b = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [14]:
b[1,1]

np.int64(5)

In [15]:
b[2] = np.array([10,10,10])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 10, 10]])

In [17]:
b[:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 10, 10]])

In [18]:
b[:,1]

array([ 2,  5, 10])

In [19]:
b[1,:]

array([4, 5, 6])

In [23]:
np.random.seed(1)
np.random.rand(5,2)

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01]])

In [24]:
np.random.seed(1)
np.random.randn(5,2)

array([[ 1.62434536, -0.61175641],
       [-0.52817175, -1.07296862],
       [ 0.86540763, -2.3015387 ],
       [ 1.74481176, -0.7612069 ],
       [ 0.3190391 , -0.24937038]])

In [26]:
np.random.seed(1)
np.random.randint(low=0, high=100, size=(10,10), dtype=int)

array([[37, 12, 72,  9, 75,  5, 79, 64, 16,  1],
       [76, 71,  6, 25, 50, 20, 18, 84, 11, 28],
       [29, 14, 50, 68, 87, 87, 94, 96, 86, 13],
       [ 9,  7, 63, 61, 22, 57,  1,  0, 60, 81],
       [ 8, 88, 13, 47, 72, 30, 71,  3, 70, 21],
       [49, 57,  3, 68, 24, 43, 76, 26, 52, 80],
       [41, 82, 15, 64, 68, 25, 98, 87,  7, 26],
       [25, 22,  9, 67, 23, 27, 37, 57, 83, 38],
       [ 8, 32, 34, 10, 23, 15, 87, 25, 71, 92],
       [74, 62, 46, 32, 88, 23, 55, 65, 77,  3]])

In [27]:
a = np.arange(10)

In [29]:
a * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
a - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [31]:
a > 2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [32]:
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [33]:
a.min()

np.int64(0)

In [34]:
a.max()

np.int64(9)

In [35]:
a.sum()

np.int64(45)

In [36]:
a.mean()

np.float64(4.5)

In [37]:
a.std()

np.float64(2.8722813232690143)

In [38]:
a.var()

np.float64(8.25)