In [40]:
import numpy as np

In [41]:
u = np.array([1,2,3])
v = np.array([4,5,6])

In [42]:
u.shape[0]

3

In [43]:
u + v

array([5, 7, 9])

In [44]:
u * v # not vector multiplication

array([ 4, 10, 18])

In [45]:
def multiply_vectors(u, v):
    assert u.shape[0] == v.shape[0]

    size = u.shape[0]
    result = 0.0

    for i in range(size):
        result += u[i] * v[i]
    
    return result

In [46]:
multiply_vectors(u, v)

np.float64(32.0)

In [47]:
np.dot(u, v)

np.int64(32)

In [48]:
U = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
v = np.array([1,2,3])

In [49]:
def multiply_matrix_vector(U, v):
    assert U.shape[1] == v.shape[0]

    size = U.shape[1]
    result = np.zeros(size)

    for i in range(size):
        result[i] = multiply_vectors(U[i], v)

    return result

In [50]:
multiply_matrix_vector(U, v)

array([14., 32., 50.])

In [51]:
np.dot(U, v)

array([14, 32, 50])

In [52]:
def multiply_matrix_matrix(U, V):
    assert U.shape[1] == V.shape[0]

    n_rows = U.shape[0]
    n_cols = V.shape[1]
    result = np.zeros((n_rows, n_cols))

    for i in range(n_cols):
        vi = V[:, i]
        Uvi = multiply_matrix_vector(U, vi)
        result[:, i] = Uvi

    return result


In [53]:
V = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

multiply_matrix_matrix(U, V)

array([[ 30.,  36.,  42.],
       [ 66.,  81.,  96.],
       [102., 126., 150.]])

In [54]:
np.dot(U, V)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [55]:
I = np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
V = np.array([
    [1,4,7],
    [0,9,1],
    [7,8,9]
])

In [64]:
np.linalg.det(V)

np.float64(-340.0000000000001)

In [65]:
V_inv = np.linalg.inv(V)
V_inv

array([[-0.21470588, -0.05882353,  0.17352941],
       [-0.02058824,  0.11764706,  0.00294118],
       [ 0.18529412, -0.05882353, -0.02647059]])

In [66]:
np.dot(V_inv, V)

array([[ 1.00000000e+00,  0.00000000e+00, -8.32667268e-17],
       [ 4.33680869e-19,  1.00000000e+00,  6.50521303e-18],
       [ 6.93889390e-18,  2.77555756e-17,  1.00000000e+00]])